# Generated by Django 4.1.7 on 2023-04-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0003_slider_field_alter_navbar_field_cart_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image1/brand_images/')),
            ],
        ),
    ]
