# Generated by Django 4.1.7 on 2023-04-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0005_footer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_Model_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Footer_model_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textfield', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Footer_model',
        ),
    ]
