# Generated by Django 4.1.7 on 2023-04-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0006_footer_model_services_footer_model_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Site_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Footer_model_tag',
        ),
    ]
