# Generated by Django 4.1.7 on 2023-04-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0007_social_site_link_delete_footer_model_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image1/about_page/')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
            ],
        ),
    ]
