# Generated by Django 4.1.7 on 2023-04-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0009_about_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('tel_no', models.CharField(max_length=15)),
                ('info_link', models.TextField()),
                ('opening_hours', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='about_team',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
