# Generated by Django 4.1.7 on 2023-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0011_login_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='static/image1/mobile_images/')),
                ('product_name', models.CharField(max_length=50)),
                ('product_rate', models.FloatField()),
            ],
        ),
    ]
