# Generated by Django 4.1.7 on 2023-04-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0012_mobile_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College1.mobile_model')),
            ],
        ),
    ]
