# Generated by Django 4.1.7 on 2023-04-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0014_mobile_model_product_brand_delete_popup_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile_model',
            name='product_brand',
        ),
        migrations.AddField(
            model_name='mobile_model',
            name='product_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobile_model',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mobile_model',
            name='product_feature1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile_model',
            name='product_feature2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile_model',
            name='product_feature3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile_model',
            name='product_feature4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile_model',
            name='product_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mobile_model',
            name='product_policy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mobile_model',
            name='product_shipping',
            field=models.TextField(null=True),
        ),
    ]
