# Generated by Django 4.1.7 on 2023-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0015_remove_mobile_model_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='static/image1/tablet_images/')),
                ('product_name', models.CharField(max_length=50)),
                ('product_rate', models.FloatField()),
                ('product_color', models.CharField(max_length=20, null=True)),
                ('product_description', models.TextField(null=True)),
                ('product_info', models.TextField(null=True)),
                ('product_policy', models.TextField(null=True)),
                ('product_shipping', models.TextField(null=True)),
                ('product_feature1', models.CharField(max_length=100, null=True)),
                ('product_feature2', models.CharField(max_length=100, null=True)),
                ('product_feature3', models.CharField(max_length=100, null=True)),
                ('product_feature4', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
