# Generated by Django 4.1.7 on 2023-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0018_product_model_delete_accessories_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
