# Generated by Django 4.1.7 on 2023-04-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0019_product_model_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='static/image1/mobile_images/')),
                ('product_name', models.CharField(max_length=50)),
                ('product_rate', models.FloatField()),
                ('product_color', models.CharField(max_length=20)),
                ('product_description', models.TextField()),
                ('product_info', models.TextField()),
                ('product_policy', models.TextField()),
                ('product_shipping', models.TextField()),
                ('product_feature1', models.CharField(max_length=100)),
                ('product_feature2', models.CharField(max_length=100)),
                ('product_feature3', models.CharField(max_length=100)),
                ('product_feature4', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
