# Generated by Django 4.1.7 on 2023-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0021_remove_cart_model_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_model',
            name='product_image',
            field=models.ImageField(upload_to='static/image1/temp/'),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='product_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
