# Generated by Django 4.1.7 on 2023-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0022_alter_cart_model_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='product_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
