# Generated by Django 4.1.7 on 2023-04-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0023_alter_product_model_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Response_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('msg', models.TextField()),
            ],
        ),
    ]
