# Generated by Django 4.1.7 on 2023-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0025_product_model_product_add_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
    ]
