# Generated by Django 4.1.7 on 2023-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College1', '0026_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_model',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
